### ISSUE TITLE
Improvement(s) for eu_dst

### ISSUE THREAD

**Issue by 3-14152898** [avrdudes/avr-libc#956]
As already reported, function `eu_dst()` in time.h incorrectly sets DST at 2:00 UTC instead of 1:00 UTC (see https://en.wikipedia.org/wiki/Daylight_saving_time_by_country). Conversely it uses division and modulo operations which are unnecessary besides CPU intensive — the call to `gmtime()` is intensive enough and provides everything required for the computation.

Attached is my suggestion as a patch — which Github still pretends to refuse even though it ends with `.patch` so here it is as a ZIP : [eu_dst.h.patch.zip](https://github.com/avrdudes/avr-libc/files/14918071/eu_dst.h.patch.zip) . I also implemented a demo sketch in Wokwi for illustration purposes: https://wokwi.com/projects/394687644304051201

Cheers.

**Comment by dl8dtl** [comment]
Well, the usual method to submit patches to Github is to fork the repository, prepare everything in a branch in your forked copy, and after uploading, follow the steps to create a pull request.
Keeping to this standard procedure makes it easier for maintainers to look at your work, optionally suggest modifications, and eventually integrate everything – all without fiddling with individual patch files.

**Comment by sprintersb** [comment]
Added the proposed patch. However, implementing functions in headers is usually frowned upon; so maybe this warrents a new module?

**Comment by sprintersb** [comment]
..moved `eu_dst` into its own module.

However, `use_dst` suffers from the same problems I guess? I.e. wrong / bogus computation and implements code in a header.

**Comment by sprintersb** [comment]
Done. Also moved `usa_dst` into its own module.

**Comment by sprintersb** [comment]
> It is not so unusual, for instance, in C++ to have implementations use only one single header file. The same can be achieved in C and GCC `__attribute__((always_inline))` could be used in order to enforce inlining.

C++ works differently. It uses features like `comdat` to make sure multiple implementations of the same template instance will not skark multiple instances in the binary. We don't have that in C.

(Always) inline is appropriate for (very) small functions, but not for functions that large.

**Comment by sprintersb** [comment]
> Conversely it uses division and modulo operations which are unnecessary besides CPU intensive — the call to `gmtime()` is intensive enough and provides everything required for the computation.

Question: `gmtime_r` looks much more CPU intense than the original implementation of `eu_dst`.  So the only purpose of the new implementaton is to save code space, not CPU load?

**Comment by sprintersb** [comment]
> I haven't check the implementation of `gmtime_r()` (thoroughly) but I can assure you the goal is to reduce CPU load somehow. Since modulo and division are emulated on 8-bit AVR, therefore relatively expensive, a simpler algorithm is beneficial, regardless of how `gmtime_r()` is implemented.

NACK. `gmtime_r()` is sprincled with division and module, much more than the initial `eu_dst` implementation used. So CPU load is going up. And code size will only go down when *both* functions are used in the application. I don't know enough about time applications to judge whether that is a reasonable assumption though.

> My point being that enough clock cycles are consumed in that function, so let's not waste more than necessary.

Smaller code does not imply less CPU cyles.  In particular when functions like  `gmtime_r()` are called that are very expensive, much more expensive than the original `eu_dst` implementation.

> Consequently though the code may save some space and might happen to be more readable — it's true that I had to spend quite some time on the original code to understand what it did and why that way...

Readable and comprehensible soures are nice, but what's paramnount for the and user is functionality and performance.

We have many sources in the code base that are not easy to digest, like assembly code for floating point.

Increasing their understandability could be achieved by providing better comment and documentation, for example.  Just using expensive code because you understand it better is is not a reason for introcucing expensive code...

I am more and more inclined to revert that stuff.
