### ISSUE TITLE
time.h: function mktime() is off by 1h when [EU] DST is active

### ISSUE THREAD

**Issue by 3-14152898** [avrdudes/avr-libc#967]
Hi.

I *believe* there is a bug somewhere in AVR libc with function `mktime()`: if I initialize system time with a time structure that corresponds to a date when DST is active **and** `eu_dst` is used, then the resulting time is one hour later than expected. Here's some minimal code to show the issue:

```c
#include <avr/io.h>
#include <stdint.h>
#include <time.h>
#include <util/eu_dst.h>

const int16_t year_offset = 1900;
struct tm t;

void set(int8_t h, int8_t m, int8_t day, int8_t month, int16_t year)
{
  t.tm_isdst = 0;
  t.tm_sec = 0;
  t.tm_hour = h;
  t.tm_min = m;
  t.tm_mday = day;
  t.tm_mon = month - 1;
  t.tm_year = year - year_offset;
  // mktime() is expected to interpret t as *local* time
  set_system_time(mktime(&t));
}

void show()
{
  char buffer[64];

  time_t timer = time(NULL);
  localtime_r(&timer, &t);

  strftime(buffer, 64, "[%z] %d/%m/%Y %T", &t);
  /* TODO: Print buffer */
}

int main()
{
  set_dst(eu_dst);

  set(/* hour:min */ 12, 0, /* day/mon */ 1, 1, /* year */ 2020);
  show();	/* OK: [+0100] 01/01/2020 12:00:00 */

  set(11, 55, 3, 5, 2024);
  show();	/* Not OK: [+0200] 03/05/2024 12:55:00, should be 11:55 */
}
```
I know I have submitted a while ago a patch for `eu_dst` — the switch hour was incorrect — but the issue happens with it as well. I don't exclude I'm using these functions incorrectly though. I have saved an Arduino sketch on Wokwi to actually print the results: https://wokwi.com/projects/399672040050420737

I have no idea what to fix so far however. I'll try fiddling some more and might add a comment as soon as I find a workaround — assuming there's a problem indeed. Also note the problem happens regardless of whether I'm using `set_zone()` or not.

Cheers,
π

**Comment by sprintersb** [comment]
I don't understand that.  What function does "latter" refer to?  There is only 1 function mentioned so far, which is `mktime`.

**Comment by sprintersb** [comment]
The problem is that I don't understand that sentence, so I cannot reword it.

**Comment by dl8dtl** [comment]
I just verified, the documentation basically documents what used to be written in C99.

The C23 standard explains it a bit better, it adds these two sentences:

"If the local time to be used for the conversion is one that includes Daylight Saving
Time adjustments, a positive or zero value for tm_isdst causes the mktime function to perform the
conversion as if Daylight Saving Time, respectively, is or is not in effect for the specified time. A
negative value causes it to attempt to determine whether Daylight Saving Time is in effect for the
specified time; if it determines that Daylight Saving Time is in effect it produces the same result
as an equivalent call with a positive tm_isdst value, otherwise it produces the same result as an
equivalent call with a tm_isdst value of zero."

I wonder whether we are allowed to copy that text verbatim …

**Comment by dl8dtl** [comment]
But maybe it's easier to find our own wording.

**Comment by dl8dtl** [comment]
> I believe it is a good thing to have AVR libc documentation updated accordingly to avoid any confusion.

That's why I reopened the issue, and tagged it accordingly.

**Comment by dl8dtl** [comment]
OK, thanks. I was only looking into the WG14 (C standard) drafts, but C++ is technically the same here. (The C standard text is actually more accurate, but that one would suffice.)

Means we can somehow globally point to them, and then include that text.

**Comment by dl8dtl** [comment]
It was just easier to add my own wording.
